import {useEffect,useState} from 'react';
import {FlaskConical,Play,Save,Archive} from 'lucide-react';
import SnapshotPanel from './SnapshotPanel';
type Summary={id:string;name:string;revision:number;updatedAt:string};
type Row=Summary&{content:string};
export default function App(){
  const [view,setView]=useState<'rules'|'offline'>('rules');
  const [items,setItems]=useState<Summary[]>([]);const [selected,setSelected]=useState('alpha');const [row,setRow]=useState<Row|null>(null);const [draft,setDraft]=useState('');const [analysis,setAnalysis]=useState<unknown>(null);const [status,setStatus]=useState('Ready');
  useEffect(()=>{fetch('/api/flags').then(r=>r.json()).then(setItems)},[]);
  useEffect(()=>{setStatus('Loading');fetch('/api/flags/'+selected).then(r=>r.json()).then((value:Row)=>{setRow(value);setDraft(value.content);setStatus('Loaded')})},[selected]);
  async function save(){if(!row)return;setStatus('Saving');const response=await fetch('/api/flags/'+row.id,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({content:draft,revision:row.revision})});const value=await response.json();if(!response.ok){setStatus('Revision conflict');return}setRow(value);setStatus('Saved')}
  async function analyze(){if(!row)return;setStatus('Analyzing');const response=await fetch('/api/flags/'+row.id+'/analyze',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({content:draft})});setAnalysis(await response.json());setStatus('Ready')}
  return <main className="shell"><header className="topbar"><FlaskConical size={20}/><strong>Feature Evaluation Lab</strong><small>Local workspace</small><nav className="view-switch"><button className={view==='rules'?'active':''} onClick={()=>setView('rules')}><FlaskConical size={14}/>Rules</button><button className={view==='offline'?'active':''} onClick={()=>setView('offline')}><Archive size={14}/>Offline export</button></nav></header>{view==='rules'?<section className="workspace"><aside className="pane"><h2>Items</h2><div className="list">{items.map(item=><button className={item.id===selected?'active':''} onClick={()=>setSelected(item.id)} key={item.id}>{item.name}<br/><small>Revision {item.revision}</small></button>)}</div></aside><section className="pane"><div className="toolbar"><button className="primary" onClick={save}><Save size={15}/>Save</button><button onClick={analyze}><Play size={15}/>Analyze</button><span>{status}</span></div><textarea aria-label="Content" value={draft} onChange={event=>setDraft(event.target.value)}/></section><aside className="pane"><h2>Inspection</h2><span className="pill">{selected}</span><pre>{JSON.stringify(analysis??row,null,2)}</pre></aside></section>:<section className="workspace offline-workspace"><div className="pane offline-intro"><h2><Archive size={16}/>Offline client distribution</h2><p>Export evaluation snapshots bound to a release, generate incremental packages from an older snapshot to a newer one, and simulate the offline client's application: baseline identity and integrity are verified before anything changes, and the result must match the declared target root digest.</p><ul><li>Object digests cover规范配置, 分群 and the derived dependency topology.</li><li>Deltas list added / replaced / deleted objects by identity.</li><li>Apply is atomic: complete target snapshot, or the original stays untouched.</li></ul></div><SnapshotPanel/></section>}</main>;
}
